name: Yaml Lint
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        config_data: |
          extends: relaxed
          rules:
            new-lines: disable
            new-line-at-end-of-file: disable
            line-length: disable
            empty-values: enable